# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

volumes:
  mongodb_data:

services:
  # -------------=== b4e tp   ===-------------
  b4e-tp-3:
    image: thanhnv2303/b4e:fast
    container_name: b4e-tp-3
    volumes:
      - '.:/project/sawtooth-b4e'
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-3:4004
        echo b4e-tp-3 connect
      "

  b4e-tp-4:
    image: thanhnv2303/b4e:fast
    container_name: b4e-tp-4
    volumes:
      - '.:/project/sawtooth-b4e'
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-4:4004
        echo b4e-tp-4 connect
      "
  b4e-tp-5:
    image: thanhnv2303/b4e:fast
    container_name: b4e-tp-5
    volumes:
      - '.:/project/sawtooth-b4e'
    command: |
      bash -c "
        sleep 1
        b4e-tp -v -C tcp://validator-5:4004
        echo b4e-tp-5 connect
      "

  # -------------=== settings tp ===-------------

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: settings-tp-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL

  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: settings-tp-4
    expose:
      - 4004
    command: settings-tp -C tcp://validator-4:4004
    stop_signal: SIGKILL
  settings-tp-5:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: settings-tp-5
    expose:
      - 4004
    command: settings-tp -C tcp://validator-4:4004
    stop_signal: SIGKILL

  # -------------=== shell ===-------------

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell
    volumes:
      - ./pbft-shared:/pbft-shared
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  # -------------=== validators ===-------------

  validator-3:
    image: hyperledger/sawtooth-validator:chime
    container_name: validator-3
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - '4007:4004'
      - '8803:8800'
    volumes:
      - ./pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-3.priv ]; then
         cp /pbft-shared/validators/validator-3.pub   /etc/sawtooth/keys/validator.pub
         cp /pbft-shared/validators/validator-3.priv   /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
         sawadm keygen
         mkdir -p /pbft-shared/validators || true
         cp /etc/sawtooth/keys/validator.pub   /pbft-shared/validators/validator-3.pub
         cp /etc/sawtooth/keys/validator.priv   /pbft-shared/validators/validator-3.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://${HOST_IP_2}:8803 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://${HOST_IP_1}:8800 \
          --peers tcp://${HOST_IP_1}:8801 \
          --peers tcp://${HOST_IP_1}:8802
      "

  validator-4:
    image: hyperledger/sawtooth-validator:chime
    container_name: validator-4
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - '4008:4004'
      - '8804:8800'
    volumes:
      - ./pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-4.priv ]; then
          cp /pbft-shared/validators/validator-4.pub   /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-4.priv   /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub   /pbft-shared/validators/validator-4.pub
          cp /etc/sawtooth/keys/validator.priv   /pbft-shared/validators/validator-4.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://${HOST_IP_2}:8804 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://${HOST_IP_1}:8800 \
          --peers tcp://${HOST_IP_1}:8801 \
          --peers tcp://${HOST_IP_1}:8802 \
          --peers tcp://${HOST_IP_2}:8803
      "

  validator-5:
    image: hyperledger/sawtooth-validator:chime
    container_name: validator-5
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - '4009:4004'
      - '8805:8800'
    volumes:
      - ./pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-5.priv ]; then
          cp /pbft-shared/validators/validator-5.pub   /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-5.priv   /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub   /pbft-shared/validators/validator-5.pub
          cp /etc/sawtooth/keys/validator.priv   /pbft-shared/validators/validator-5.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://${HOST_IP_2}:8805 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://${HOST_IP_1}:8800 \
          --peers tcp://${HOST_IP_1}:8801 \
          --peers tcp://${HOST_IP_1}:8802 \
          --peers tcp://${HOST_IP_2}:8803\
          --peers tcp://${HOST_IP_2}:8804
      "


  # -------------=== pbft engines ===-------------

  pbft-3:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: pbft-engine-3
    command: pbft-engine -vv --connect tcp://validator-3:5050
    stop_signal: SIGKILL

  pbft-4:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: pbft-engine-4
    command: pbft-engine -vv --connect tcp://validator-4:5050
    stop_signal: SIGKILL
  pbft-5:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: pbft-engine-5
    command: pbft-engine -vv --connect tcp://validator-5:5050
    stop_signal: SIGKILL


  b4e-statistic:
    image: thanhnv2303/b4e:fast
    container_name: b4e-statistic
    volumes:
      - '.:/project/sawtooth-b4e'
    depends_on:
      - postgres-statistic
      - validator-2
    ports:
      - '${STATISTIC_PORT}:8000'
    command: |
      bash -c "
        b4e-statistic.py init \
        --db-name b4e-statistic\
        --db-host postgres-statistic \
        --db-user ${USERNAME} \
        --db-password ${PASSWORD} \
        -vv
        sleep 3
        b4e-statistic.py subscribe \
        -B b4e-statistic:8000 \
        --db-name b4e-statistic\
        --db-host postgres-statistic \
        --db-user ${USERNAME} \
        --db-password ${PASSWORD} \
        -C tcp://validator-3:4004 \
        -vv
      "
  postgres-statistic:
    image: postgres:alpine
    container_name: postgres-statistic
    restart: always
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: b4e-statistic
    expose:
      - 5432
    ports:
      - '5432:5432'
